---
- name: Multi-Subnet IPAM + GCP Provisioning
  hosts: 192.168.116.129
  gather_facts: no
  connection: ssh

  vars_files:
    - vars/common.yml
    - vars/paths.yml

  vars:
    region_map:
      AO: asia-south1
      EU: europe-west1
      AS: asia-east1
      NA: us-central1

  tasks:

    # Fail early
    - fail:
        msg: "Variable 'subnets' missing"
      when: subnets is not defined

    - fail:
        msg: "'subnets' should be list"
      when: subnets is not iterable

    - fail:
        msg: "Max 5 subnets allowed per execution"
      when: (subnets | length) > 5


    # Init report
    - name: Init subnet_report
      set_fact:
        subnet_report: []


    # Load CSVs
    - name: Load Env.csv
      read_csv:
        path: "{{ env_csv }}"
      register: env_raw

    - set_fact:
        env_data: "{{ env_raw.list }}"

    - name: Load Subnet.csv
      read_csv:
        path: "{{ subnet_csv }}"
      register: subnet_raw

    - set_fact:
        subnet_data: "{{ subnet_raw.list }}"


    # Process subnets
    - name: Process each subnet request
      include_tasks: subnet_unit.yml
      loop: "{{ subnets }}"
      loop_control:
        loop_var: req


    # Render HTML Report
    - name: Render HTML report
      template:
        src: "templates/subnet_report.html.j2"
        dest: "/tmp/subnet_report.html"
      delegate_to: localhost
      run_once: true


    # Determine final mail subject
    - name: Check if any subnet failed
      set_fact:
        final_mail_subject: >
          {{ 'GCP Subnet Creation Report (FAILED)' 
              if (subnet_report | selectattr('status','equalto','FAILED') | list | length > 0)
              else 'GCP Subnet Creation Report (SUCCESS)' 
          }}
      delegate_to: localhost
      run_once: true


    # Send mail
    - name: Send HTML mail
      mail:
        host: smtp.gmail.com
        port: 587
        username: "{{ email_user }}"
        password: "{{ email_password }}"
        to: "{{ email_to }}"
        subject: "{{ final_mail_subject }}"
        subtype: html
        body: "{{ lookup('file','/tmp/subnet_report.html') }}"
      delegate_to: localhost
      run_once: true
