---
- name: Multi-Subnet IPAM + GCP Provisioning
  hosts: 192.168.116.129
  gather_facts: no
  connection: ssh

  vars:
    env_csv: "/opt/GCP/Env.csv"
    subnet_csv: "/opt/GCP/Subnet.csv"
    calc_script: "/opt/GCP/scripts/calc_next_subnet.py"
    gcp_sa_file: "/opt/GCP/sa.json"

    region_map:
      AO: asia-south1
      EU: europe-west1
      AS: asia-east1
      NA: us-central1

  tasks:

    # ----------------------------------------------------------
    # 0. Validate inputs
    # ----------------------------------------------------------
    - fail:
        msg: "'subnets' variable missing"
      when: subnets is not defined

    - fail:
        msg: "'subnets' should be a list"
      when: subnets is not iterable

    - fail:
        msg: "Max 5 subnets per execution"
      when: subnets | length > 5


    # ----------------------------------------------------------
    # 1. Init report list
    # ----------------------------------------------------------
    - name: Initialize subnet report list
      set_fact:
        subnet_report: []


    # ----------------------------------------------------------
    # 2. Load CSV data
    # ----------------------------------------------------------
    - name: Read Env.csv
      read_csv:
        path: "{{ env_csv }}"
      register: env_raw

    - set_fact:
        env_data: "{{ env_raw.list }}"

    - name: Read Subnet.csv
      read_csv:
        path: "{{ subnet_csv }}"
      register: subnet_raw

    - set_fact:
        subnet_data: "{{ subnet_raw.list }}"


    # ----------------------------------------------------------
    # 3. Run subnet creation loop
    # ----------------------------------------------------------
    - name: Process each subnet request
      include_tasks: subnet_unit.yml
      loop: "{{ subnets }}"
      loop_control:
        loop_var: req
        index_var: batch_index


    # ----------------------------------------------------------
    # 4. Generate HTML report
    # ----------------------------------------------------------
    - name: Render HTML email report
      template:
        src: "templates/subnet_report.html.j2"
        dest: "/tmp/subnet_report.html"
      delegate_to: localhost
      run_once: true


    # ----------------------------------------------------------
    # 5. Send Email
    # ----------------------------------------------------------
    - name: Send HTML email with report
      mail:
        host: smtp.gmail.com
        port: 587
        username: "{{ email_user }}"
        password: "{{ email_password }}"
        to: "{{ email_to }}"
        subject: "GCP Multi-Subnet Creation Report"
        subtype: html
        body: "{{ lookup('file','/tmp/subnet_report.html') }}"
      delegate_to: localhost
      run_once: true
